# Site
# repository: p16pyla/resume-sw
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dionisis Pylarinos
title: This is my Resume
email: p16pyla@ionio.gr
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  p16pyla
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: DinineSets
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
 # icon: fas fa-globe
 # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: 21363078_1461677473900111_2024132859_n.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Dionisis and I'm student at Ionian Univeristy. I am intersting for operation business systems(ERP) and i am olso a deejay.I am 23 years old in the 5th university student year.I live in Corfu until i finish my studys and iam from Athens
  I am most skilled in: c,c++,java and sql
  I also use Music softwares for djs and producers(rekordbox,fl studio)
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University projects
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
         # - title:  sproogen/modern-resume-theme
           # icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The most intrested for me
        description: | # this will include new lines to allow paragraphs
               I build an online pharmacy with 300 products inside from zero.Î¤here you can make your online purchases with many payment methods all over Greece through a wide range of products.It is very easy and at the same time very detailed to to explore it
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Not yet
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        # caption: November 2017 - Present
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            In most jobs they ask about previous service where you gain your experience. I have no experience but I have a lot of appetite for work and exploring new projects. I have learned a lot in my university and I have still searched a lot on my own in programming languages and databases. 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Ionian University
        caption: 2016 - 202?
        sub_title: BSc Computer Science
        quote: >
          The first Greek University, the Ionian Academy, was founded in Corfu in 1824 and was the first modern-day Greek school of modern times and the academy of the United States of the Ionian Islands. The Department of Informatics has been operating since the academic year 2004-05. The subject of the Department is both theoretical and applied Informatics.
        description: | # this will include new lines to allow paragraphs
         At Ionian University we have learned many things, but the ones to which he has given more attention are the  teamwork and working to tight deadlines. I enjoy my time on university and i learn a lot about a healthy work life balance in the future.  
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      other hobbies:
      
      - Gaming
      - Djing
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
